### ISSUE TITLE
ROIs fail to display in Ophys NWB File.

### ISSUE THREAD

**Issue by rcpeene** [NeurodataWithoutBorders/nwbwidgets#236] opened 2022-11-08 19:33 UTC
When using nwbwidgets within a Jupyter Notebook to examine an Ophys NWB File, opening `processing > ophys > image segmentation` and then pressing `Display ROIs` yields an error, and nothing gets displayed. The expected behavior is for the ROIs to be displayed. Here is the traceback.

```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\nwbwidgets\ophys.py:188, in PlaneSegmentation2DWidget.on_button_click(self, b)
    184 elif len(self.categorical_columns) > 1:
    185     self.cat_controller = widgets.Dropdown(
    186         options=list(self.categorical_columns), description="color by"
    187     )
--> 188     self.fig = self.show_plane_segmentation_2d(
    189         color_by=self.cat_controller.value, **self.kwargs
    190     )
    192     def on_change(change):
    193         if change["new"] and isinstance(change["new"], dict):

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\nwbwidgets\ophys.py:295, in PlaneSegmentation2DWidget.show_plane_segmentation_2d(self, color_wheel, color_by, threshold, fig, width, ref_image)
    293         kwargs.update(showlegend=True)
    294         aux_leg.append(plane_seg_hover_df[color_by][i])
--> 295     c = color_wheel[np.where(cats == plane_seg_hover_df[color_by][i])[0][0]]
    296     kwargs.update(
    297         line_color=c,
    298         name=str(plane_seg_hover_df[color_by][i]),
    299         legendgroup=str(plane_seg_hover_df[color_by][i]),
    300     )
    302 x, y = self.compute_outline(i, threshold)

IndexError: list index out of range

```

**Comment by bendichter** [comment] 2022-11-08 19:57
It looks like you have more ROI categories than we can colors. We can fix this by modulo-ing into the `color_by` list.

**Comment by bendichter** [comment] 2022-11-08 20:15
I wasn't able to reproduce. Here's the code I tried:

```python
from pynwb.testing.mock.ophys import mock_PlaneSegmentation
import numpy as np
from nwbwidgets.ophys import PlaneSegmentation2DWidget

ps = mock_PlaneSegmentation(n_rois=0)
ps.add_column("category", "category")

for i in range(50):
    image_mask = np.zeros((100, 100))

    # randomly generate example image masks
    x = np.random.randint(0, 95)
    y = np.random.randint(0, 95)
    image_mask[x:x + 5, y:y + 5] = 1

    # add image mask to plane segmentation
    ps.add_roi(image_mask=image_mask, category=str(i))
    
PlaneSegmentation2DWidget(ps)
```

![image](https://user-images.githubusercontent.com/844306/200666192-b581b7a7-3962-47d9-b11e-c3f9c9e30b69.png)


what are the values of the column you are trying to view the data by?

**Comment by bendichter** [comment] 2022-11-08 20:33
ok, I was able to reproduce the error with 

```python
from pynwb.testing.mock.ophys import mock_PlaneSegmentation
import numpy as np
from nwbwidgets.ophys import PlaneSegmentation2DWidget

ps = mock_PlaneSegmentation(n_rois=0)
ps.add_column("category", "category")


for i in range(50):
    image_mask = np.zeros((100, 100))

    # randomly generate example image masks
    x = np.random.randint(0, 95)
    y = np.random.randint(0, 95)
    image_mask[x:x + 5, y:y + 5] = 1

    # add image mask to plane segmentation
    ps.add_roi(
        image_mask=image_mask,
        category=str(i//2),
    )
    
PlaneSegmentation2DWidget(ps)
```

**Comment by rcpeene** [comment] 2022-11-08 20:41
In my data, there are 17 ROIs. Weird if that is too many.

**Comment by bendichter** [comment] 2022-11-08 20:56
It's the number of categories that's the problem, but I fixed it with the PR above. Just needs to be reviewed and merged

**Comment by bendichter** [comment] 2022-11-09 16:02
@rcpeene this is now fixed in the latest dev branch

**Closed** 2022-11-09 16:02 UTC
